package elec332.core.util;

import com.google.common.collect.Lists;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

/**
 * Created by Elec332.
 */
@SuppressWarnings("unused")
public class MCModInfo {

	public static void createMCModInfo(FMLPreInitializationEvent event, String modid, String name, String version, String credits, String desc, String url, String logo, String[] authors) {
		ModMetadata meta = event.getModMetadata();
		meta.autogenerated = false;
		meta.modId = modid;
		meta.name = name;
		meta.version = version;
		meta.credits = credits;
		meta.description = desc;
		meta.url = url;
		meta.logoFile = logo;
		meta.authorList = Lists.newArrayList(authors);
	}

	@SuppressWarnings("deprecation")
	public static void createMCModInfo(FMLPreInitializationEvent event, String credits, String desc, String url, String logo, String[] authors) {
		createMCModInfo(event, event.getModMetadata().modId, event.getModMetadata().name, credits, desc, url, logo, authors);
	}

	public static void createMCModInfoElec(FMLPreInitializationEvent event, String desc, String url, String logo, String[] authors) {
		createMCModInfo(event, "Created by Elec332", desc, url, logo, authors);
	}

	public static void createMCModInfo(FMLPreInitializationEvent event, String modid, String name, String credits, String desc, String url, String logo, String[] authors) {
		ModMetadata meta = event.getModMetadata();
		meta.autogenerated = false;
		meta.modId = modid;
		meta.name = name;
		meta.credits = credits;
		meta.description = desc;
		meta.url = url;
		meta.logoFile = logo;
		meta.authorList = Lists.newArrayList(authors);
	}
}
